# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dena/lab_cpp/EncryptionAlgorithmRGR_AES_added/EncryptionAlgorithmRGR_Aes

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dena/lab_cpp/EncryptionAlgorithmRGR_AES_added/EncryptionAlgorithmRGR_Aes/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dena/lab_cpp/EncryptionAlgorithmRGR_AES_added/EncryptionAlgorithmRGR_Aes/build/CMakeFiles /home/dena/lab_cpp/EncryptionAlgorithmRGR_AES_added/EncryptionAlgorithmRGR_Aes/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dena/lab_cpp/EncryptionAlgorithmRGR_AES_added/EncryptionAlgorithmRGR_Aes/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named EncryptionAlgorithmRGR

# Build rule for target.
EncryptionAlgorithmRGR: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 EncryptionAlgorithmRGR
.PHONY : EncryptionAlgorithmRGR

# fast build rule for target.
EncryptionAlgorithmRGR/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EncryptionAlgorithmRGR.dir/build.make CMakeFiles/EncryptionAlgorithmRGR.dir/build
.PHONY : EncryptionAlgorithmRGR/fast

#=============================================================================
# Target rules for targets named gronsfeld_cipher

# Build rule for target.
gronsfeld_cipher: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gronsfeld_cipher
.PHONY : gronsfeld_cipher

# fast build rule for target.
gronsfeld_cipher/fast:
	$(MAKE) $(MAKESILENT) -f plugins/gronsfeld/CMakeFiles/gronsfeld_cipher.dir/build.make plugins/gronsfeld/CMakeFiles/gronsfeld_cipher.dir/build
.PHONY : gronsfeld_cipher/fast

#=============================================================================
# Target rules for targets named vernam_cipher

# Build rule for target.
vernam_cipher: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vernam_cipher
.PHONY : vernam_cipher

# fast build rule for target.
vernam_cipher/fast:
	$(MAKE) $(MAKESILENT) -f plugins/vernam/CMakeFiles/vernam_cipher.dir/build.make plugins/vernam/CMakeFiles/vernam_cipher.dir/build
.PHONY : vernam_cipher/fast

#=============================================================================
# Target rules for targets named aes_cipher

# Build rule for target.
aes_cipher: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 aes_cipher
.PHONY : aes_cipher

# fast build rule for target.
aes_cipher/fast:
	$(MAKE) $(MAKESILENT) -f plugins/aes/CMakeFiles/aes_cipher.dir/build.make plugins/aes/CMakeFiles/aes_cipher.dir/build
.PHONY : aes_cipher/fast

src/CipherPlugin.o: src/CipherPlugin.cpp.o
.PHONY : src/CipherPlugin.o

# target to build an object file
src/CipherPlugin.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EncryptionAlgorithmRGR.dir/build.make CMakeFiles/EncryptionAlgorithmRGR.dir/src/CipherPlugin.cpp.o
.PHONY : src/CipherPlugin.cpp.o

src/CipherPlugin.i: src/CipherPlugin.cpp.i
.PHONY : src/CipherPlugin.i

# target to preprocess a source file
src/CipherPlugin.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EncryptionAlgorithmRGR.dir/build.make CMakeFiles/EncryptionAlgorithmRGR.dir/src/CipherPlugin.cpp.i
.PHONY : src/CipherPlugin.cpp.i

src/CipherPlugin.s: src/CipherPlugin.cpp.s
.PHONY : src/CipherPlugin.s

# target to generate assembly for a file
src/CipherPlugin.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EncryptionAlgorithmRGR.dir/build.make CMakeFiles/EncryptionAlgorithmRGR.dir/src/CipherPlugin.cpp.s
.PHONY : src/CipherPlugin.cpp.s

src/DynamicLibrary.o: src/DynamicLibrary.cpp.o
.PHONY : src/DynamicLibrary.o

# target to build an object file
src/DynamicLibrary.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EncryptionAlgorithmRGR.dir/build.make CMakeFiles/EncryptionAlgorithmRGR.dir/src/DynamicLibrary.cpp.o
.PHONY : src/DynamicLibrary.cpp.o

src/DynamicLibrary.i: src/DynamicLibrary.cpp.i
.PHONY : src/DynamicLibrary.i

# target to preprocess a source file
src/DynamicLibrary.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EncryptionAlgorithmRGR.dir/build.make CMakeFiles/EncryptionAlgorithmRGR.dir/src/DynamicLibrary.cpp.i
.PHONY : src/DynamicLibrary.cpp.i

src/DynamicLibrary.s: src/DynamicLibrary.cpp.s
.PHONY : src/DynamicLibrary.s

# target to generate assembly for a file
src/DynamicLibrary.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EncryptionAlgorithmRGR.dir/build.make CMakeFiles/EncryptionAlgorithmRGR.dir/src/DynamicLibrary.cpp.s
.PHONY : src/DynamicLibrary.cpp.s

src/FileProcessor.o: src/FileProcessor.cpp.o
.PHONY : src/FileProcessor.o

# target to build an object file
src/FileProcessor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EncryptionAlgorithmRGR.dir/build.make CMakeFiles/EncryptionAlgorithmRGR.dir/src/FileProcessor.cpp.o
.PHONY : src/FileProcessor.cpp.o

src/FileProcessor.i: src/FileProcessor.cpp.i
.PHONY : src/FileProcessor.i

# target to preprocess a source file
src/FileProcessor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EncryptionAlgorithmRGR.dir/build.make CMakeFiles/EncryptionAlgorithmRGR.dir/src/FileProcessor.cpp.i
.PHONY : src/FileProcessor.cpp.i

src/FileProcessor.s: src/FileProcessor.cpp.s
.PHONY : src/FileProcessor.s

# target to generate assembly for a file
src/FileProcessor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EncryptionAlgorithmRGR.dir/build.make CMakeFiles/EncryptionAlgorithmRGR.dir/src/FileProcessor.cpp.s
.PHONY : src/FileProcessor.cpp.s

src/HexUtils.o: src/HexUtils.cpp.o
.PHONY : src/HexUtils.o

# target to build an object file
src/HexUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EncryptionAlgorithmRGR.dir/build.make CMakeFiles/EncryptionAlgorithmRGR.dir/src/HexUtils.cpp.o
.PHONY : src/HexUtils.cpp.o

src/HexUtils.i: src/HexUtils.cpp.i
.PHONY : src/HexUtils.i

# target to preprocess a source file
src/HexUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EncryptionAlgorithmRGR.dir/build.make CMakeFiles/EncryptionAlgorithmRGR.dir/src/HexUtils.cpp.i
.PHONY : src/HexUtils.cpp.i

src/HexUtils.s: src/HexUtils.cpp.s
.PHONY : src/HexUtils.s

# target to generate assembly for a file
src/HexUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EncryptionAlgorithmRGR.dir/build.make CMakeFiles/EncryptionAlgorithmRGR.dir/src/HexUtils.cpp.s
.PHONY : src/HexUtils.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EncryptionAlgorithmRGR.dir/build.make CMakeFiles/EncryptionAlgorithmRGR.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EncryptionAlgorithmRGR.dir/build.make CMakeFiles/EncryptionAlgorithmRGR.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EncryptionAlgorithmRGR.dir/build.make CMakeFiles/EncryptionAlgorithmRGR.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... EncryptionAlgorithmRGR"
	@echo "... aes_cipher"
	@echo "... gronsfeld_cipher"
	@echo "... vernam_cipher"
	@echo "... src/CipherPlugin.o"
	@echo "... src/CipherPlugin.i"
	@echo "... src/CipherPlugin.s"
	@echo "... src/DynamicLibrary.o"
	@echo "... src/DynamicLibrary.i"
	@echo "... src/DynamicLibrary.s"
	@echo "... src/FileProcessor.o"
	@echo "... src/FileProcessor.i"
	@echo "... src/FileProcessor.s"
	@echo "... src/HexUtils.o"
	@echo "... src/HexUtils.i"
	@echo "... src/HexUtils.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

